<?php


namespace kodCmsPlugin\models\client;


use ronashdkl\kodCms\components\FieldConfig;
use ronashdkl\kodCms\models\ListModel;
use yii\base\Model;
use yii\helpers\ArrayHelper;

/**
 * Class AboutListModel
 * @property string $text
 * @package kodCmsPlugin\models\service
 */
class ClientListModel extends ListModel
{

    public $name;
    public $image;
    public $url;
    public function rules()
    {

        return ArrayHelper::merge(parent::rules(), [
            ['image', 'string'],
            ['name', 'string'],
            ['url', 'string'],
        ]);

    }

    public function formTypes()
    {
        return [
            'name' => [
                // 'value' => $this->text,
                'type' => FieldConfig::INPUT,
            ],
            'image' => [
                // 'value' => $this->text,
                'type' => FieldConfig::IMAGE,
            ],
            'url' => [
                // 'value' => $this->text,
                'type' => FieldConfig::INPUT,
            ]
        ];
    }

    public  function displayAttributes()
    {
        return  ['name','image'];
    }

    public function validate($attributeNames = null, $clearErrors = true)
    {
        return parent::validate($attributeNames, $clearErrors); // TODO: Change the autogenerated stub
    }
}
