<?php


namespace kodCmsPlugin\models\about;


use ronashdkl\kodCms\components\FieldConfig;

use ronashdkl\kodCms\models\ListModel;
use yii\base\Model;
use yii\helpers\ArrayHelper;

/**
 * Class AboutListModel
 * @property string $text
 * @package kodCmsPlugin\models\service
 */
class AboutListModel extends ListModel
{

    public $question;
    public $answer;

    public function rules()
    {

        return ArrayHelper::merge(parent::rules(), [
            ['question', 'string'],
            ['answer', 'required']
        ]);

    }

    public function formTypes()
    {
        return [
            'question' => [
                // 'value' => $this->text,
                'type' => FieldConfig::INPUT,
            ],
            'answer' => [
                // 'value' => $this->text,
                'type' => FieldConfig::CKEDITOR,
            ]
        ];
    }

    public  function displayAttributes()
    {
        return  ['question'];
    }

    public function validate($attributeNames = null, $clearErrors = true)
    {
        return parent::validate($attributeNames, $clearErrors); // TODO: Change the autogenerated stub
    }
}
