<?php


namespace kodCmsPlugin\widgets\sections;


abstract class SectionWidget extends \ronashdkl\kodCms\widgets\sections\SectionWidget
{
public function init()
{
    parent::init(); // TODO: Change the autogenerated stub


  //  die;
}
}
